apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName }}-nginx-deploy
  labels:
    app: {{ .Values.releaseName }}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.releaseName }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Values.releaseName }}-nginx
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

