apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.releaseName }}-service
  labels:
    {{- toYaml .Values.serviceAccount.label | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.releaseName }}-nginx
